---
- name: Gather the rpm package facts
  package_facts:
    manager: auto

- name: Check and install dependencies
  shell: |
    {{ sudo_cmd }}
    yum install -y {{ dependencies }}
    exit
  when: item not in ansible_facts.packages
  with_items: "{{ dependencies }}"
