---
- name: Create backup dir if it does not already exist
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: '0770'

- name: Create openldap backup dir if it does not already exist
  file:
    path: "{{ backup_dir }}openldap"
    state: directory
    mode: '0770'

- name: Copy backup script to backup dir
  copy:
    src: backup.sh
    dest: "{{ backup_dir }}openldap/"
    mode: '0755'
